name: Build Pixel5 Android14 KernelSU SUSFS (Non-GKI)

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:

jobs:
  build-redbull-4-19:
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential flex bison libssl-dev libelf-dev \
            libncurses5-dev gcc-aarch64-linux-gnu make

      - name: Install repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod +x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Clone AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git

      - name: Init kernel source
        run: |
          mkdir redbull
          cd redbull

          repo init -u https://android.googlesource.com/kernel/manifest \
            -b android-msm-redbull-4.19-android14-qpr3 --repo-rev=v2.54
          repo sync -c -j$(nproc) --no-tags --fail-fast

          cd private/msm-google
          git checkout 7b0944645172

      - name: Add KernelSU (Non-GKI)
        run: |
          cd redbull/private/msm-google
          curl -LSs https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh \
            | bash -s nongki

      - name: Enable KernelSU + SUSFS (correct way)
        run: |
          cd redbull/private/msm-google

          scripts/config --file arch/arm64/configs/redbull_defconfig \
            -e CONFIG_KSU \
            -e CONFIG_KALLSYMS \
            -e CONFIG_KALLSYMS_ALL

      - name: Disable defconfig check
        run: |
          cd redbull/private/msm-google
          sed -i 's/check_defconfig//' build.config.redbull

      - name: Build kernel (Non-GKI)
        run: |
          cd redbull
          BUILD_AOSP_KERNEL=1 ./build_redbull.sh

      - name: Pack AnyKernel3
        run: |
          cp redbull/out/android-msm-pixel-4.19/dist/Image.lz4 AnyKernel3/Image
          cd AnyKernel3
          zip -r ../Pixel5-A14-4.19-KernelSU-SUSFS.zip .

      - name: Upload kernel zip
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-ZIP
          path: Pixel5-A14-4.19-KernelSU-SUSFS.zip

      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: boot-images
          path: |
            redbull/out/android-msm-pixel-4.19/dist/boot.img
            redbull/out/android-msm-pixel-4.19/dist/vendor_boot.img
            redbull/out/android-msm-pixel-4.19/dist/dtbo.img
